//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentes_psicologicos
    {
        public int idPaciente { get; set; }
        public short Anciedad { get; set; }
        public short Depresion { get; set; }
        public short Bipolaridad { get; set; }
        public short Esquizofrenia { get; set; }
        public short Fobias { get; set; }
        public short Psicosis { get; set; }
        public string Otros { get; set; }
        public int Paciente_idPaciente { get; set; }
    }
}
