//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentes_familiares
    {
        public int idPaciente { get; set; }
        public short Diabetes { get; set; }
        public short Cancer { get; set; }
        public short Obesidad { get; set; }
        public short Cardiovasculares { get; set; }
        public short Alcoholismo { get; set; }
        public short Muertes_Prematuras { get; set; }
        public int Paciente_idPaciente { get; set; }
    }
}
