//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentes_patologicos
    {
        public int idPaciente { get; set; }
        public short Hepatitis { get; set; }
        public short Diabetes { get; set; }
        public short Hipertension { get; set; }
        public short Epilepsia { get; set; }
        public short ETS { get; set; }
        public short Asma { get; set; }
        public short Alergias { get; set; }
        public short Antecedentes_Quirugicos { get; set; }
        public string Otros { get; set; }
        public int Paciente_idPaciente { get; set; }
    }
}
