//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class barrio
    {
        public int Persona_id { get; set; }
        public string Barrio1 { get; set; }
        public string Localidad { get; set; }
        public int Persona_Persona_id { get; set; }
        public int Ciudad_Persona_id { get; set; }
    }
}
