//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int Doctor_Id { get; set; }
        public string Num_Matricula { get; set; }
        public string Cuit_Cuil { get; set; }
        public string Especialidad { get; set; }
        public int Persona_Persona_id { get; set; }
    }
}
