//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergencia
    {
        public int Persona_id { get; set; }
        public string Nombre { get; set; }
        public string Tel_Emergencia { get; set; }
        public string Nombre_Emergencia { get; set; }
        public string Apellido_Emerg { get; set; }
        public string Direccion_Emerg { get; set; }
        public int Persona_Persona_id { get; set; }
    }
}
