//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitos_toxicos
    {
        public int idPaciente { get; set; }
        public short Alcohol { get; set; }
        public short Tabaco { get; set; }
        public short Aspirinas { get; set; }
        public short Tranquilizantes { get; set; }
        public short Excitantes { get; set; }
        public short Otros { get; set; }
        public int Paciente_idPaciente { get; set; }
    }
}
