//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HistoriaClinicaEntities : DbContext
    {
        public HistoriaClinicaEntities()
            : base("name=HistoriaClinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afiliacion> afiliacions { get; set; }
        public virtual DbSet<antecedentes_familiares> antecedentes_familiares { get; set; }
        public virtual DbSet<antecedentes_patologicos> antecedentes_patologicos { get; set; }
        public virtual DbSet<antecedentes_psicologicos> antecedentes_psicologicos { get; set; }
        public virtual DbSet<barrio> barrios { get; set; }
        public virtual DbSet<calle> calles { get; set; }
        public virtual DbSet<ciudad> ciudads { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<domicilio> domicilios { get; set; }
        public virtual DbSet<emergencia> emergencias { get; set; }
        public virtual DbSet<habitos_toxicos> habitos_toxicos { get; set; }
        public virtual DbSet<institucion> institucions { get; set; }
        public virtual DbSet<institucion_has_doctor> institucion_has_doctor { get; set; }
        public virtual DbSet<obrasocial> obrasocials { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<provincia> provincias { get; set; }
    }
}
