//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HC.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int idPaciente { get; set; }
        public string PesoActual { get; set; }
        public string Altura { get; set; }
        public string GrupoSanguineo { get; set; }
        public string Peso_Habitual { get; set; }
        public string CreenciaReligiosa { get; set; }
        public string Vacunas_Completo { get; set; }
        public string Vacunas_faltantes { get; set; }
        public int Persona_Persona_id { get; set; }
        public short TomaMedicamentos { get; set; }
        public string Pacientecol { get; set; }
    }
}
